before_script:
  - nvm install 11.4.0
  - nvm use 11.4.0
  - npm install -g grunt-cli
  - npm install
script:
  - ./node_modules/eslint/bin/eslint.js -c .eslintrc javascripts/
addons:
  sauce_connect:
    username: "MusikAnimal"
    access_key: "71bb4995-3679-4b53-89d3-9d1516da1089"
branches:
  only:
    - master
